spring:
  profiles: local

  datasource:
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 9090

security:
  jwt:
    config:
      signature-key: local_government_info
      expire-in-milliseconds: 1800000

logging:
  level:
    ROOT: trace
---
